/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cadastropessoa;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Professor
 */
public class TelaCadPessoa extends javax.swing.JInternalFrame {

    TelaPrincipal telaPrincipal;
    private int posicao = -1;
    /**
     * Creates new form TelaCadPessoa
     */
    public TelaCadPessoa(TelaPrincipal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
        this.posicao = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pessoas");

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");
        jLabel2.setToolTipText("");

        jLabel3.setText("E-mail:");

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Listar Pessoas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("◀");
        jButton3.setToolTipText("Navegar para a pessoa a esquerda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("▶");
        jButton4.setToolTipText("Navegar para a pessoa a direita");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Excluir pessoa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtEndereco)
                            .addComponent(txtEmail))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Gravar
        if(camposPreenchidos()){
            Pessoa pessoa = new Pessoa();
            pessoa.setNome(txtNome.getText());
            pessoa.setEndereco(txtEndereco.getText());
            pessoa.setEmail(txtEmail.getText());
            String mensagem  = "";
            //se a variável posicao == -1 gravar novo registro
            // senão (!=) atualizar registro
            if(posicao == -1){
                //adicionar esta pessoa no array listaPessoas na tela principal:
                telaPrincipal.adicionarPessoaLista(pessoa);
                mensagem = "Pessoa cadastrada com sucesso!";
            }else{
                telaPrincipal.atualizarPessoaLista(pessoa, posicao);
                mensagem = "Pessoa atualizada com sucesso!";
            }
            limparTela();
            posicao = -1;
            JOptionPane.showMessageDialog(null, 
                    mensagem);
        }else{
            JOptionPane.showMessageDialog(null, 
                    "Preencha todos os campos!");
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Listar pessoas
        listarPessoas();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Navegar para direita
        List<Pessoa> lstPessoa = telaPrincipal.getListaPessoa();
        posicao++; //posicao = posicao+1
        if(posicao < lstPessoa.size()){
            Pessoa pessoa = lstPessoa.get(posicao);
            //posicao++; //posicao = posicao+1
            txtNome.setText(pessoa.getNome());
            txtEndereco.setText(pessoa.getEndereco());
            txtEmail.setText(pessoa.getEmail());
        }else{
            JOptionPane.showMessageDialog(null, "Não existem mais pessoas no cadastro");
            posicao = -1;
            limparTela();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Navegar para à esquerda
        List<Pessoa> lstPessoa = telaPrincipal.getListaPessoa();
        posicao--; //posicao = posicao-1
        if(posicao > -1){
            Pessoa pessoa = lstPessoa.get(posicao);
            txtNome.setText(pessoa.getNome());
            txtEndereco.setText(pessoa.getEndereco());
            txtEmail.setText(pessoa.getEmail());
        }else{
            JOptionPane.showMessageDialog(null, "Não existem mais pessoas no cadastro");
            posicao = -1;
            limparTela();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Botao de excluir pessoa
        List<Pessoa> lstPessoa = telaPrincipal.getListaPessoa();

        // Verifica se existe uma pessoa válida sendo exibida.
        if (posicao < 0 || posicao >= lstPessoa.size()) {
            JOptionPane.showMessageDialog(null,
                    "Não existe uma pessoa válida para excluir.");
            return;
        }

        Pessoa pessoa = lstPessoa.get(posicao);

        int resposta = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente excluir essa pessoa?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            telaPrincipal.removerPessoaLista(posicao);

            // Ajusta a posição para continuar exibindo um registro válido.
            if (lstPessoa.isEmpty()) {
                posicao = -1;
                limparTela();
            } else if (posicao >= lstPessoa.size()) {
                // O último registro foi excluído: exibe o novo último.
                posicao = lstPessoa.size() - 1;
                exibirPessoa(lstPessoa.get(posicao));
            } else {
                // Primeiro ou registro intermediário foi excluído:
                // exibe o registro que ocupou a posição removida.
                exibirPessoa(lstPessoa.get(posicao));
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
   
    // Exibe os dados de uma pessoa nos campos da tela.
    private void exibirPessoa(Pessoa pessoa) {
        txtNome.setText(pessoa.getNome());
        txtEndereco.setText(pessoa.getEndereco());
        txtEmail.setText(pessoa.getEmail());
    }

    //método para limpar os campos da tela
    private void limparTela(){
        txtNome.setText("");
        txtEndereco.setText("");
        txtEmail.setText("");
        txtNome.requestFocusInWindow();
    }
    
    //método para adicionar todas as pessoas da lista
    private void listarPessoas(){
        List<Pessoa> lstPessoa = telaPrincipal.getListaPessoa();
        String texto = "";
        for(Pessoa p : lstPessoa){
            //+= ==> texto = texto + concatenar
            texto += p.toString() + "\n --------- \n";
        }
        JOptionPane.showMessageDialog(null, texto);
    }

    private boolean camposPreenchidos() {
        boolean resposta = true;
        //vamos validar os campos
        if(txtNome.getText().length() == 0){
            resposta = false;
        }
        if(txtEndereco.getText().length() == 0 && resposta){
            resposta = false;
        }
        if(txtEmail.getText().length() == 0 && resposta){
            resposta = false;
        }
        return resposta;
    }
    
}
